# Generated by Django 4.1 on 2022-08-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='meessages',
            new_name='messages',
        ),
    ]
